### ISSUE TITLE
please add a option for the color like -H

### ISSUE THREAD

**Issue by MaxPeal** [xfgusta/strace-with-colors#1]
please add a option for the color like -H in this patch 
https://sourceforge.net/p/strace/mailman/strace-devel/thread/1490959253-6522-1-git-send-email-chenjingpiao%40gmail.com/#msg35760809

**Comment by mikroskeem** [comment]
Could implement [NO_COLOR](https://no-color.org/) as well with this

**Comment by xfgusta** [comment]
> please add a option for the color like -H in this patch https://sourceforge.net/p/strace/mailman/strace-devel/thread/1490959253-6522-1-git-send-email-chenjingpiao%40gmail.com/#msg35760809

It's difficult to add an option like this now due to the way I implemented the patch. It requires a complete rework, and I'm not planning to do that. But I can add an option to disable the colored output, which is a *very* ugly code, but it works.

**Comment by xfgusta** [comment]
> Could implement [NO_COLOR](https://no-color.org/) as well with this

I added an option called `--no-color`. The program also checks the `NO_COLOR` environment variable .

**Comment by xfgusta** [comment]
![image](https://user-images.githubusercontent.com/66979446/162021778-7bd3bed0-2d11-4a5f-b7bd-e5cf016b9204.png)

**Comment by xfgusta** [comment]
I pushed the changes. I will update both Copr and AUR packages very soon. I think the `--no-color` option quite satisfies the `-H` option, but the colored output will be the default.

@MaxPeal you can close the issue now if you want.

Edit: It's already available on Copr and AUR.

**Comment by MaxPeal** [comment]
Thank you for the fast changes.
