### ISSUE TITLE
Writing to file should strip escape codes

### ISSUE THREAD

**Issue by SuperSandro2000** [xfgusta/strace-with-colors#2]
When I am supplying strace with `-o` and write the log to a file the escape codes are also written to the file. I think they should be stripped before to easily search and navigate the file with a text editor.

**Comment by xfgusta** [comment]
I agree with you, it makes no sense to save a file with a bunch of escape codes. However, I recently added an option that disables the colored output (#1), which also applies to the `-o` option. You can use the `-N` or `--no-color` options or set the `NO_COLOR` environment variable.

![image](https://user-images.githubusercontent.com/66979446/163660468-a0310ced-b7ca-477e-a706-dd3d8a6517d5.png)

**Comment by SuperSandro2000** [comment]
I am using the latest patch but it didn't seem to imply no color for the following command `strace -o log -f code`.

**Comment by xfgusta** [comment]
Have you tried `strace -No log -f code`? The `-o` option alone doesn't disable the colored output, you have to use `-N` or `--no-color` option or set `NO_COLOR`.

![image](https://user-images.githubusercontent.com/66979446/163696698-1610f193-7eed-4b3f-8c48-a4428927a4ff.png)

**Comment by SuperSandro2000** [comment]
Yeah, I was suggestion to automatically add -N when -o is set.

**Comment by xfgusta** [comment]
Added https://github.com/xfgusta/strace-with-colors/commit/473bb19832a56ab9434c65d9386b973aeebf208f. I will update both Copr and AUR packages soon.

**Comment by xfgusta** [comment]
I updated the packages. You can close the issue now if you want.
