### ISSUE TITLE
Bringing this upstream

### ISSUE THREAD

**Issue by TheJJ** [xfgusta/strace-with-colors#3]
I'd love to see this in upstream [`strace`](https://github.com/strace/strace), you should consider submitting it for review soon so the patch can be improve until the maintainers are happy :)

Thanks for your work, I've been missing colored output (and relying for vim-coloring instead) for years.

**Comment by xfgusta** [comment]
> I'd love to see this in upstream [strace](https://github.com/strace/strace)

Me too, but it's almost impossible with this patch.

The escape sequences are hard-coded in the strings. For example:

```diff
+#define C_RESET   "\033[0m"
+#define C_CYAN    "\033[36m"
```

```diff
 	if (!addr) {
-		tprints("NULL");
+		tprints(C_CYAN "NULL" C_RESET);
 		return -1;
 	}
```
The `--no-color` option (#1) just removes them before printing, which is quite inefficient I would say. To do it properly and with maintainability in mind, it requires a more structural change, which goes beyond this patch. I don't think it's worth bringing this upstream.

> Thanks for your work, I've been missing colored output (and relying for vim-coloring instead) for years.

Thanks, I'm glad you liked it.

**Comment by yesudeep** [comment]
I'd like to mention the use of `bat` as a makeshift alternative if the patch cannot be merged into upstream.

```
strace foo_binary 2>&1 | bat -l strace
```

See: https://github.com/sharkdp/bat
