### ISSUE TITLE
Use automatic coloring by default

### ISSUE THREAD

**Issue by TheJJ** [xfgusta/strace-with-colors#4]
Like many other tools do (e.g. `ls`), this should also automatically coloring by checking if the terminal is a tty, and then colorize.
The `--color` cli option should then have three values:
- `auto` (default, based on the `ioctl(stdout, TCGETS, ...)` being `-1 ENOTTY` or `0`
- `never` (turn off coloring)
- `always` (turn on coloring)

**Comment by xfgusta** [comment]
Sounds like a good idea. I would probably remove the `--no-color` option in favor of `--color=never`, but instead of "never" being the default  (like `ls`), I would set "auto" instead. I will try to implement it soon.
