### ISSUE TITLE
What color scheme is in the screenshot?

### ISSUE THREAD

**Issue by Kyuuhachi** [xfgusta/strace-with-colors#7]
I know this is completely unrelated to the actual project, but that color scheme looks way better than my terminal.

**Comment by xfgusta** [comment]
Hi @Kyuuhachi. Sorry for the late reply, I was away from my PC for a few weeks.

Here is the color scheme used:

| FG | Name    | Color     |
| -- | ------- | --------- |
| 0  | Black   | `#2d3139` |
| 1  | Red     | `#e06c75` |
| 2  | Green   | `#98c379` |
| 3  | Yellow  | `#e5c07b` |
| 4  | Blue    | `#528bff` |
| 5  | Magenta | `#c678dd` |
| 6  | Cyan    | `#56b6c2` |
| 7  | White   | `#d7dae0` |

The patch doesn't use bright colors, so you won't need them.

**Comment by xfgusta** [comment]
It might be helpful to add this to the README. What do you think?
